import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const CLI = join(import.meta.dirname, '..', 'src', 'cli.mjs');
const run = (cmd, options = {}) => execSync(`node ${CLI} ${cmd}`, { encoding: 'utf-8', timeout: 15000, ...options });
const runWithHome = (cmd, home, options = {}) => run(cmd, {
  ...options,
  env: { ...process.env, HOME: home },
});

let tmpDir;

beforeEach(() => {
  tmpDir = join(import.meta.dirname, '..', '.test-tmp-' + Date.now());
  mkdirSync(tmpDir, { recursive: true });
});

afterEach(() => {
  if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true, force: true });
});

describe('install', () => {
  it('installs claude skills with banner', () => {
    const out = run('install --tool claude', { cwd: tmpDir });
    assert.ok(out.includes('gantry 已安装'));
    assert.ok(out.includes('claude'));
    assert.ok(existsSync(join(tmpDir, 'CLAUDE.md')));
    assert.ok(existsSync(join(tmpDir, '.claude', 'skills')));
    const content = readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf8');
    assert.ok(content.includes('<!-- BEGIN gantry -->'));
    assert.ok(content.includes('<!-- END gantry -->'));
    const skillDirs = readdirSync(join(tmpDir, '.claude', 'skills'));
    assert.ok(skillDirs.length > 0, 'should produce skill folders');
    assert.ok(skillDirs.includes('gantry-next'), 'should include public orchestration skills');
    assert.ok(skillDirs.includes('gantry-context'), 'should include context command group');
    assert.ok(skillDirs.includes('gantry-knowledge'), 'should include knowledge command group');
    assert.ok(skillDirs.includes('gantry-debug'), 'should keep debug as a standalone public skill');
    assert.ok(skillDirs.includes('gantry-fast'), 'should keep fast as a standalone public skill');
    assert.ok(!skillDirs.includes('gantry-design'), 'should not expose internal phase-only skills');
    assert.ok(!skillDirs.includes('gantry-task'), 'should not expose internal phase-only skills');
    assert.ok(!skillDirs.includes('gantry-check-req'), 'should not expose retired requirement gate skill');
    assert.ok(!skillDirs.includes('gantry-doubt'), 'should not expose retired adversarial review skill');
    const sample = readFileSync(join(tmpDir, '.claude', 'skills', skillDirs[0], 'SKILL.md'), 'utf8');
    assert.ok(sample.includes('GENERATED by gantry'));
  });

  it('installs cursor files', () => {
    run('install --tool cursor', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.cursor', 'rules', '00-system.mdc')));
    const rules = readdirSync(join(tmpDir, '.cursor', 'rules'));
    assert.ok(rules.some(name => name.includes('gantry-context')), 'should include context command group rule');
    assert.ok(rules.some(name => name.includes('gantry-knowledge')), 'should include knowledge command group rule');
    assert.ok(!rules.some(name => name.includes('i-intel-scan')), 'should not expose internal scan phase rule');
    assert.ok(!rules.some(name => name.includes('c-curator')), 'should not expose internal curator phase rule');
  });

  it('installs codex AGENTS.md + .agents/skills/', () => {
    run('install --tool codex', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, 'AGENTS.md')));
    assert.ok(!existsSync(join(tmpDir, 'CLAUDE.md')));
    const skillsDir = join(tmpDir, '.agents', 'skills');
    assert.ok(existsSync(skillsDir));
    const skills = readdirSync(skillsDir);
    assert.ok(skills.length > 0, 'should produce skill folders');
    assert.ok(skills.some(s => s.startsWith('gantry-')), 'should include gantry-* skills');
    assert.ok(skills.includes('gantry-next'), 'should include public orchestration skills');
    assert.ok(skills.includes('gantry-context'), 'should include context command group');
    assert.ok(skills.includes('gantry-knowledge'), 'should include knowledge command group');
    assert.ok(skills.includes('gantry-debug'), 'should keep debug as a standalone public skill');
    assert.ok(skills.includes('gantry-fast'), 'should keep fast as a standalone public skill');
    assert.ok(!skills.includes('gantry-design'), 'should not expose internal phase-only skills');
    assert.ok(!skills.includes('gantry-task'), 'should not expose internal phase-only skills');
    assert.ok(!skills.includes('gantry-check-req'), 'should not expose retired requirement gate skill');
    assert.ok(!skills.includes('gantry-doubt'), 'should not expose retired adversarial review skill');
    const sampleSkill = join(skillsDir, skills[0], 'SKILL.md');
    assert.ok(existsSync(sampleSkill), `${sampleSkill} should exist`);
    const sample = readFileSync(sampleSkill, 'utf8');
    assert.ok(sample.includes('GENERATED by gantry'));
  });

  it('installs copilot files', () => {
    run('install --tool copilot', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.github', 'copilot-instructions.md')));
    assert.ok(existsSync(join(tmpDir, '.github', 'prompts')));
    const prompts = readdirSync(join(tmpDir, '.github', 'prompts'));
    assert.ok(prompts.includes('gantry-context.prompt.md'), 'should include context command group prompt');
    assert.ok(prompts.includes('gantry-knowledge.prompt.md'), 'should include knowledge command group prompt');
    assert.ok(!prompts.includes('i-intel-scan.prompt.md'), 'should not expose internal scan phase prompt');
    assert.ok(!prompts.includes('c-curator.prompt.md'), 'should not expose internal curator phase prompt');
  });

  it('auto-detects cursor from existing .cursor/', () => {
    mkdirSync(join(tmpDir, '.cursor'), { recursive: true });
    const out = run('install', { cwd: tmpDir });
    assert.ok(out.includes('cursor'));
    assert.ok(existsSync(join(tmpDir, '.cursor', 'rules')));
  });

  it('auto-installs all detected local agents', () => {
    mkdirSync(join(tmpDir, '.cursor'), { recursive: true });
    writeFileSync(join(tmpDir, 'AGENTS.md'), '# Existing agents\n');
    writeFileSync(join(tmpDir, 'CLAUDE.md'), '# Existing claude\n');
    const out = run('install', { cwd: tmpDir });
    assert.ok(out.includes('工具: claude'));
    assert.ok(out.includes('工具: codex'));
    assert.ok(out.includes('工具: cursor'));
    assert.ok(existsSync(join(tmpDir, '.claude', 'skills')));
    assert.ok(existsSync(join(tmpDir, '.agents', 'skills')));
    assert.ok(existsSync(join(tmpDir, '.cursor', 'rules')));
  });

  it('defaults to claude when no IDE detected', () => {
    const out = run('install', { cwd: tmpDir });
    assert.ok(out.includes('claude'));
    assert.ok(existsSync(join(tmpDir, 'CLAUDE.md')));
  });

  it('accepts legacy claude-code tool alias', () => {
    const out = run('install --tool claude-code', { cwd: tmpDir });
    assert.ok(out.includes('claude'));
    assert.ok(existsSync(join(tmpDir, 'CLAUDE.md')));
  });

  it('is idempotent (re-install overwrites)', () => {
    run('install --tool codex', { cwd: tmpDir });
    run('install --tool codex', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, 'AGENTS.md')));
  });

  it('install initializes project state and selected local agent integration', () => {
    run('install --tool codex', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.gantry/planning', 'STATE.md')));
    assert.ok(existsSync(join(tmpDir, '.gantry/planning', 'config.json')));
    const config = JSON.parse(readFileSync(join(tmpDir, '.gantry/planning', 'config.json'), 'utf8'));
    assert.equal(config.stages.change.requiresApproval, true);
    assert.equal(config.stages.design.requiresApproval, true);
    assert.equal(config.stages.integration.requiresApproval, true);
    assert.equal(config.stages.requirement.requiresApproval, undefined);
    assert.equal(config.stages.review.requiresApproval, undefined);
    assert.equal(config.stages['ui-design'].condition, 'ui-impact');
    assert.equal(('check' + 'point') in config.stages.change, false);
    assert.ok(existsSync(join(tmpDir, '.gantry/core/phases', '0-change.md')));
    assert.ok(existsSync(join(tmpDir, '.gantry/core/agents', 'planner.md')));
    assert.ok(existsSync(join(tmpDir, 'AGENTS.md')));
    assert.ok(existsSync(join(tmpDir, '.agents/skills/gantry-change', 'SKILL.md')));
    assert.ok(!existsSync(join(tmpDir, '.agents/skills/gantry-init', 'SKILL.md')));
    assert.ok(!existsSync(join(tmpDir, '.gantry/planning', 'ROADMAP.md')));
    assert.ok(!existsSync(join(tmpDir, '.gantry/planning', 'context-pack.json')));
  });

  it('generated change skill matches current bootstrap contract', () => {
    run('install --tool codex', { cwd: tmpDir });
    const changeSkill = readFileSync(join(tmpDir, '.agents/skills/gantry-change', 'SKILL.md'), 'utf8');
    assert.ok(changeSkill.includes('若 pack 不存在'));
    assert.ok(changeSkill.includes('gantry change "<描述>"'));
    assert.ok(changeSkill.includes('明确要求停在人工确认关卡时禁止执行'));
    assert.ok(!changeSkill.includes('完成后执行 `next.onSuccess` (失败走 `next.onFailure`)'));
  });

  it('rejects unknown tool', () => {
    assert.throws(() => run('install --tool unknown', { cwd: tmpDir }), /未知工具/);
  });

  it('-g installs all tools into global agent directories', () => {
    const home = join(tmpDir, 'home');
    mkdirSync(home, { recursive: true });
    const out = runWithHome('install -g', home, { cwd: tmpDir });
    assert.ok(out.includes('工具: claude (global)'));
    assert.ok(out.includes('工具: codex (global)'));
    assert.ok(out.includes('工具: cursor (global)'));
    assert.ok(out.includes('工具: copilot (global)'));
    assert.ok(existsSync(join(home, '.claude', 'CLAUDE.md')));
    assert.ok(existsSync(join(home, '.claude', 'skills')));
    assert.ok(existsSync(join(home, '.codex', 'AGENTS.md')));
    assert.ok(existsSync(join(home, '.codex', 'skills')));
    assert.ok(existsSync(join(home, '.cursor', 'rules')));
    assert.ok(existsSync(join(home, '.github', 'copilot-instructions.md')));
  });

  it('-g --tool installs only the selected global agent', () => {
    const home = join(tmpDir, 'home');
    mkdirSync(home, { recursive: true });
    const out = runWithHome('install -g --tool codex', home, { cwd: tmpDir });
    assert.ok(out.includes('工具: codex (global)'));
    assert.ok(!out.includes('工具: claude (global)'));
    assert.ok(existsSync(join(home, '.codex', 'AGENTS.md')));
    assert.ok(!existsSync(join(home, '.claude')));
  });
});

describe('auto', () => {
  it('uses autonomous.maxStagesPerRun from project config by default', () => {
    run('install', { cwd: tmpDir });
    const configPath = join(tmpDir, '.gantry/planning', 'config.json');
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    config.autonomous.maxStagesPerRun = 5;
    writeFileSync(configPath, JSON.stringify(config, null, 2));

    const out = run('auto', { cwd: tmpDir });
    assert.ok(out.includes('自主模式: 最多推进 5 个阶段'));

    const state = readFileSync(join(tmpDir, '.gantry/planning', 'STATE.md'), 'utf8');
    assert.ok(state.includes('- **已执行阶段数**: `0 / 5`'));
  });

  it('auto 步数只取 config.autonomous.maxStagesPerRun（--stages 已移除，不再覆盖）', () => {
    run('install', { cwd: tmpDir });
    const configPath = join(tmpDir, '.gantry/planning', 'config.json');
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    config.autonomous.maxStagesPerRun = 5;
    writeFileSync(configPath, JSON.stringify(config, null, 2));

    // 即便传入已废弃的 --stages 2，也应被忽略，仍按配置的 5 推进
    const out = run('auto --stages 2', { cwd: tmpDir });
    assert.ok(out.includes('自主模式: 最多推进 5 个阶段'));

    const state = readFileSync(join(tmpDir, '.gantry/planning', 'STATE.md'), 'utf8');
    assert.ok(state.includes('- **已执行阶段数**: `0 / 5`'));
  });
});

describe('uninstall', () => {
  it('removes all generated files', () => {
    run('install --tool claude', { cwd: tmpDir });
    const out = run('uninstall', { cwd: tmpDir });
    assert.ok(out.includes('已卸载'));
    assert.ok(!existsSync(join(tmpDir, 'CLAUDE.md')));
  });

  it('does not remove non-generated files', () => {
    run('install --tool claude', { cwd: tmpDir });
    writeFileSync(join(tmpDir, 'README.md'), '# My Project\n');
    run('uninstall', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, 'README.md')));
  });

  it('cleans empty directories', () => {
    run('install --tool cursor', { cwd: tmpDir });
    run('uninstall', { cwd: tmpDir });
    assert.ok(!existsSync(join(tmpDir, '.cursor')));
  });

  it('cleans codex .agents/skills/ directory tree', () => {
    run('install --tool codex', { cwd: tmpDir });
    run('uninstall', { cwd: tmpDir });
    assert.ok(!existsSync(join(tmpDir, '.agents')));
    assert.ok(!existsSync(join(tmpDir, 'AGENTS.md')));
    assert.ok(!existsSync(join(tmpDir, '.gantry/core/agents')));
  });

  it('--all removes .gantry/planning/', () => {
    run('install --tool codex', { cwd: tmpDir });
    run('uninstall --all', { cwd: tmpDir });
    assert.ok(!existsSync(join(tmpDir, 'AGENTS.md')));
    assert.ok(!existsSync(join(tmpDir, '.gantry/planning')));
  });

  it('preserves .gantry/planning/ without --all', () => {
    run('install --tool codex', { cwd: tmpDir });
    run('uninstall', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.gantry/planning')));
  });

  it('reports nothing when no generated files found', () => {
    const out = run('uninstall', { cwd: tmpDir });
    assert.ok(out.includes('未找到'));
  });

  it('-g uninstalls global agent files', () => {
    const home = join(tmpDir, 'home');
    mkdirSync(home, { recursive: true });
    runWithHome('install -g --tool codex', home, { cwd: tmpDir });
    const out = runWithHome('uninstall -g --tool codex', home, { cwd: tmpDir });
    assert.ok(out.includes('已卸载'));
    assert.ok(!existsSync(join(home, '.codex', 'AGENTS.md')));
    assert.ok(!existsSync(join(home, '.codex', 'skills')));
  });
});
