import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const CLI = join(import.meta.dirname, '..', 'src', 'cli.mjs');
const run = (cmd, options = {}) => execSync(`node ${CLI} ${cmd}`, { encoding: 'utf-8', timeout: 15000, ...options });
const runWithHome = (cmd, home, options = {}) => run(cmd, {
  ...options,
  env: { ...process.env, HOME: home },
});

let tmpDir;

beforeEach(() => {
  tmpDir = join(import.meta.dirname, '..', '.test-tmp-' + Date.now());
  mkdirSync(tmpDir, { recursive: true });
});

afterEach(() => {
  if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true, force: true });
});

describe('install', () => {
  it('installs claude skills with banner', () => {
    const out = run('install --tool claude', { cwd: tmpDir });
    assert.ok(out.includes('gantry 已安装'));
    assert.ok(out.includes('claude'));
    assert.ok(existsSync(join(tmpDir, 'CLAUDE.md')));
    assert.ok(existsSync(join(tmpDir, '.claude', 'skills')));
    const content = readFileSync(join(tmpDir, 'CLAUDE.md'), 'utf8');
    assert.ok(content.includes('<!-- BEGIN gantry -->'));
    assert.ok(content.includes('<!-- END gantry -->'));
    const skillDirs = readdirSync(join(tmpDir, '.claude', 'skills'));
    assert.ok(skillDirs.length > 0, 'should produce skill folders');
    const sample = readFileSync(join(tmpDir, '.claude', 'skills', skillDirs[0], 'SKILL.md'), 'utf8');
    assert.ok(sample.includes('GENERATED by gantry'));
  });

  it('installs cursor files', () => {
    run('install --tool cursor', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.cursor', 'rules', '00-system.mdc')));
  });

  it('installs codex AGENTS.md + .agents/skills/', () => {
    run('install --tool codex', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, 'AGENTS.md')));
    assert.ok(!existsSync(join(tmpDir, 'CLAUDE.md')));
    const skillsDir = join(tmpDir, '.agents', 'skills');
    assert.ok(existsSync(skillsDir));
    const skills = readdirSync(skillsDir);
    assert.ok(skills.length > 0, 'should produce skill folders');
    assert.ok(skills.some(s => s.startsWith('gantry-')), 'should include gantry-* skills');
    const sampleSkill = join(skillsDir, skills[0], 'SKILL.md');
    assert.ok(existsSync(sampleSkill), `${sampleSkill} should exist`);
    const sample = readFileSync(sampleSkill, 'utf8');
    assert.ok(sample.includes('GENERATED by gantry'));
  });

  it('installs copilot files', () => {
    run('install --tool copilot', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.github', 'copilot-instructions.md')));
    assert.ok(existsSync(join(tmpDir, '.github', 'prompts')));
  });

  it('auto-detects cursor from existing .cursor/', () => {
    mkdirSync(join(tmpDir, '.cursor'), { recursive: true });
    const out = run('install', { cwd: tmpDir });
    assert.ok(out.includes('cursor'));
    assert.ok(existsSync(join(tmpDir, '.cursor', 'rules')));
  });

  it('auto-installs all detected local agents', () => {
    mkdirSync(join(tmpDir, '.cursor'), { recursive: true });
    writeFileSync(join(tmpDir, 'AGENTS.md'), '# Existing agents\n');
    writeFileSync(join(tmpDir, 'CLAUDE.md'), '# Existing claude\n');
    const out = run('install', { cwd: tmpDir });
    assert.ok(out.includes('工具: claude'));
    assert.ok(out.includes('工具: codex'));
    assert.ok(out.includes('工具: cursor'));
    assert.ok(existsSync(join(tmpDir, '.claude', 'skills')));
    assert.ok(existsSync(join(tmpDir, '.agents', 'skills')));
    assert.ok(existsSync(join(tmpDir, '.cursor', 'rules')));
  });

  it('defaults to claude when no IDE detected', () => {
    const out = run('install', { cwd: tmpDir });
    assert.ok(out.includes('claude'));
    assert.ok(existsSync(join(tmpDir, 'CLAUDE.md')));
  });

  it('accepts legacy claude-code tool alias', () => {
    const out = run('install --tool claude-code', { cwd: tmpDir });
    assert.ok(out.includes('claude'));
    assert.ok(existsSync(join(tmpDir, 'CLAUDE.md')));
  });

  it('is idempotent (re-install overwrites)', () => {
    run('install --tool codex', { cwd: tmpDir });
    run('install --tool codex', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, 'AGENTS.md')));
  });

  it('--init creates .gantry/planning/', () => {
    run('install --tool codex --init', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.gantry/planning', 'STATE.md')));
    assert.ok(existsSync(join(tmpDir, '.gantry/planning', 'config.json')));
  });

  it('rejects unknown tool', () => {
    assert.throws(() => run('install --tool unknown', { cwd: tmpDir }), /未知工具/);
  });

  it('-g installs all tools into global agent directories', () => {
    const home = join(tmpDir, 'home');
    mkdirSync(home, { recursive: true });
    const out = runWithHome('install -g', home, { cwd: tmpDir });
    assert.ok(out.includes('工具: claude (global)'));
    assert.ok(out.includes('工具: codex (global)'));
    assert.ok(out.includes('工具: cursor (global)'));
    assert.ok(out.includes('工具: copilot (global)'));
    assert.ok(existsSync(join(home, '.claude', 'CLAUDE.md')));
    assert.ok(existsSync(join(home, '.claude', 'skills')));
    assert.ok(existsSync(join(home, '.codex', 'AGENTS.md')));
    assert.ok(existsSync(join(home, '.codex', 'skills')));
    assert.ok(existsSync(join(home, '.cursor', 'rules')));
    assert.ok(existsSync(join(home, '.github', 'copilot-instructions.md')));
  });

  it('-g --tool installs only the selected global agent', () => {
    const home = join(tmpDir, 'home');
    mkdirSync(home, { recursive: true });
    const out = runWithHome('install -g --tool codex', home, { cwd: tmpDir });
    assert.ok(out.includes('工具: codex (global)'));
    assert.ok(!out.includes('工具: claude (global)'));
    assert.ok(existsSync(join(home, '.codex', 'AGENTS.md')));
    assert.ok(!existsSync(join(home, '.claude')));
  });
});

describe('uninstall', () => {
  it('removes all generated files', () => {
    run('install --tool claude', { cwd: tmpDir });
    const out = run('uninstall', { cwd: tmpDir });
    assert.ok(out.includes('已卸载'));
    assert.ok(!existsSync(join(tmpDir, 'CLAUDE.md')));
  });

  it('does not remove non-generated files', () => {
    run('install --tool claude', { cwd: tmpDir });
    writeFileSync(join(tmpDir, 'README.md'), '# My Project\n');
    run('uninstall', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, 'README.md')));
  });

  it('cleans empty directories', () => {
    run('install --tool cursor', { cwd: tmpDir });
    run('uninstall', { cwd: tmpDir });
    assert.ok(!existsSync(join(tmpDir, '.cursor')));
  });

  it('cleans codex .agents/skills/ directory tree', () => {
    run('install --tool codex', { cwd: tmpDir });
    run('uninstall', { cwd: tmpDir });
    assert.ok(!existsSync(join(tmpDir, '.agents')));
    assert.ok(!existsSync(join(tmpDir, 'AGENTS.md')));
  });

  it('--all removes .gantry/planning/', () => {
    run('install --tool codex --init', { cwd: tmpDir });
    run('uninstall --all', { cwd: tmpDir });
    assert.ok(!existsSync(join(tmpDir, 'AGENTS.md')));
    assert.ok(!existsSync(join(tmpDir, '.gantry/planning')));
  });

  it('preserves .gantry/planning/ without --all', () => {
    run('install --tool codex --init', { cwd: tmpDir });
    run('uninstall', { cwd: tmpDir });
    assert.ok(existsSync(join(tmpDir, '.gantry/planning')));
  });

  it('reports nothing when no generated files found', () => {
    const out = run('uninstall', { cwd: tmpDir });
    assert.ok(out.includes('未找到'));
  });

  it('-g uninstalls global agent files', () => {
    const home = join(tmpDir, 'home');
    mkdirSync(home, { recursive: true });
    runWithHome('install -g --tool codex', home, { cwd: tmpDir });
    const out = runWithHome('uninstall -g --tool codex', home, { cwd: tmpDir });
    assert.ok(out.includes('已卸载'));
    assert.ok(!existsSync(join(home, '.codex', 'AGENTS.md')));
    assert.ok(!existsSync(join(home, '.codex', 'skills')));
  });
});
