#!/usr/bin/env node
// gantry build pipeline
// Usage: node tools/build.mjs [--tool claude-code|cursor|codex|copilot|all] [--out dist]

import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync, rmSync } from 'node:fs';
import { resolve, dirname, basename, join, relative } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { loadCore, loadCommands, loadAgents } from './lib/loader.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const args = parseArgs(process.argv.slice(2));
const targets = args.tool === 'all' || !args.tool
  ? ['claude-code', 'cursor', 'codex', 'copilot']
  : [args.tool];
const outRoot = resolve(ROOT, args.out ?? 'dist');

const renderers = {
  'claude-code': await import('./renderers/claude-code.mjs'),
  cursor: await import('./renderers/cursor.mjs'),
  codex: await import('./renderers/codex.mjs'),
  copilot: await import('./renderers/copilot.mjs'),
};

const core = loadCore(ROOT);
const commands = loadCommands(join(ROOT, 'skills'));
const agents = loadAgents(join(ROOT, 'src', 'agents'));
console.log(`[build] loaded core: ${Object.keys(core.phases).length} phases, ${Object.keys(core.templates).length} templates`);
console.log(`[build] loaded ${Object.keys(commands).length} commands, ${Object.keys(agents).length} agents`);

for (const tool of targets) {
  const renderer = renderers[tool];
  if (!renderer) {
    console.error(`[build] unknown tool: ${tool}`);
    process.exitCode = 1;
    continue;
  }
  const outDir = join(outRoot, tool);
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  const files = renderer.render(core, commands, agents);
  for (const [relPath, content] of Object.entries(files)) {
    const full = join(outDir, relPath);
    mkdirSync(dirname(full), { recursive: true });
    const skipBanner = isPromptEntry(relPath);
    if (skipBanner) {
      writeFileSync(full, content);
    } else {
      const banner = bannerFor(tool, relPath, content);
      writeFileSync(full, insertBanner(content, banner));
    }
  }
  console.log(`[build] ${tool}: ${Object.keys(files).length} files -> ${relative(ROOT, outDir)}`);
}

console.log('[build] done');

// -----------------------------------------------------------------------------

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (!next || next.startsWith('--')) out[key] = true;
      else { out[key] = next; i++; }
    }
  }
  return out;
}

function bannerFor(tool, relPath, content) {
  const hash = createHash('sha256').update(content).digest('hex').slice(0, 12);
  return `<!-- GENERATED by gantry · DO NOT EDIT · tool=${tool} · path=${relPath} · sha256=${hash} -->\n`;
}

function insertBanner(content, banner) {
  if (content.startsWith('---\n')) {
    const endIdx = content.indexOf('\n---\n', 4);
    if (endIdx !== -1) {
      const insertAt = endIdx + 5;
      return content.slice(0, insertAt) + banner + content.slice(insertAt);
    }
  }
  return banner + content;
}

function isPromptEntry(relPath) {
  return relPath.startsWith('.claude/')
    || relPath.startsWith('.agents/')
    || relPath === 'CLAUDE.md'
    || relPath === 'AGENTS.md';
}
