#!/usr/bin/env node
// gantry verify pipeline
// 1. dist/* 中的 banner sha256 与实际内容一致（检测手改）
// 2. dist/* 中出现的每条 R 规则在 RULES.md 能 grep 到
// 3. phases/*.md 每个在至少一个 dist/ 中有对应产物

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { resolve, dirname, join, relative } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DIST = join(ROOT, 'dist');

let errors = 0;
let checked = 0;

if (!existsSync(DIST)) {
  console.error(`[verify] dist/ missing. run: node tools/build.mjs --tool all`);
  process.exit(1);
}

const rules = readFileSync(join(ROOT, 'docs', 'RULES.md'), 'utf8');
const rulesIds = [...rules.matchAll(/\*\*(R\d+\.\d+)(?:\s|\*|\b)/g)].map((m) => m[1]);
const ruleSet = new Set(rulesIds);
console.log(`[verify] core rules indexed: ${rulesIds.length}`);

// 1 + 2
for (const tool of readdirSync(DIST)) {
  const toolDir = join(DIST, tool);
  if (!statSync(toolDir).isDirectory()) continue;
  walk(toolDir, (file) => {
    checked++;
    const text = readFileSync(file, 'utf8');
    const banner = extractBanner(text);
    if (!banner && !isBannerSkipped(file)) {
      errors++;
      console.error(`[verify] ${rel(file)} · MISSING banner`);
      return;
    }
    const body = banner ? banner.body : text;
    if (banner) {
      const recordedHash = banner.hash;
      const realHash = createHash('sha256').update(body).digest('hex').slice(0, 12);
      if (realHash !== recordedHash) {
        errors++;
        console.error(`[verify] ${rel(file)} · HAND-EDITED (sha ${recordedHash} → ${realHash})`);
      }
    }
    if (banner && toolFromPath(file) !== banner.tool) {
      errors++;
      console.error(`[verify] ${rel(file)} · TOOL mismatch (${banner.tool} vs ${toolFromPath(file)})`);
    }
    // R 引用检查
    const refs = [...body.matchAll(/\bR(\d+\.\d+)\b/g)].map((m) => `R${m[1]}`);
    const unknown = refs.filter((r) => !ruleSet.has(r));
    if (unknown.length) {
      errors++;
      console.error(`[verify] ${rel(file)} · UNKNOWN rule refs: ${[...new Set(unknown)].join(', ')}`);
    }
  });
}

// 3. phases 覆盖
const phases = readdirSync(join(ROOT, 'phases')).filter((n) => n.endsWith('.md'));
for (const phase of phases) {
  let covered = false;
  for (const tool of readdirSync(DIST)) {
    const toolDir = join(DIST, tool);
    if (!statSync(toolDir).isDirectory()) continue;
    let found = false;
    walk(toolDir, (file) => {
      if (found) return;
      const text = readFileSync(file, 'utf8');
      if (text.includes(`phases/${phase}`)) found = true;
    });
    if (found) { covered = true; break; }
  }
  if (!covered) {
    errors++;
    console.error(`[verify] phase not distributed: phases/${phase}`);
  }
}

console.log(`[verify] files checked: ${checked}, errors: ${errors}`);
process.exit(errors > 0 ? 1 : 0);

function walk(dir, visit) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, visit);
    else if (st.isFile() && full.endsWith('.md')) visit(full);
  }
}

function rel(p) { return relative(ROOT, p); }

function extractBanner(text) {
  const pattern = /<!-- GENERATED by (?:gantry|gantry) · DO NOT EDIT · tool=([^\s]+) · path=([^\s]+) · sha256=([a-f0-9]+) -->\n/;
  const atStart = text.match(new RegExp(`^${pattern.source}`));
  if (atStart) {
    return {
      tool: atStart[1],
      path: atStart[2],
      hash: atStart[3],
      body: text.slice(atStart[0].length),
    };
  }

  if (!text.startsWith('---\n')) return null;
  const endIdx = text.indexOf('\n---\n', 4);
  if (endIdx === -1) return null;
  const insertAt = endIdx + 5;
  const afterFrontmatter = text.slice(insertAt);
  const afterMatch = afterFrontmatter.match(new RegExp(`^${pattern.source}`));
  if (!afterMatch) return null;
  return {
    tool: afterMatch[1],
    path: afterMatch[2],
    hash: afterMatch[3],
    body: text.slice(0, insertAt) + afterFrontmatter.slice(afterMatch[0].length),
  };
}

function toolFromPath(file) {
  return relative(DIST, file).split(/[\\/]/)[0];
}

function isBannerSkipped(file) {
  const parts = relative(DIST, file).split(/[\\/]/);
  const tool = parts[0];
  const relPath = parts.slice(1).join('/');
  if (tool === 'claude-code') {
    return relPath.startsWith('.claude/') || relPath === 'CLAUDE.md';
  }
  if (tool === 'codex') {
    return relPath.startsWith('.agents/') || relPath === 'AGENTS.md';
  }
  return false;
}
